name: Car Tracker Bot

on:
  schedule:
    - cron: "*/15 * * * *"   # roda a cada 15 minutos
  workflow_dispatch:        # permite rodar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install requests playwright
          playwright install chromium

      - name: Rodar bot
        run: python tracker_playwright.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
